extends Node

class_name ENUM

enum HEART_AMOUNT {EMPTY, HALF, FULL}
enum ENEMY_TYPE {TEKTITE, OCTOROK, ZORA, LEEVER, BLUE_LEEVER, ARMOS, BOULDER, 
		GHINI, LYNEL, BLUE_LYNEL, MOBLIN, BLUE_MOBLIN, BLUE_OCTOROK, PEAHAT,
		BLUE_TEKTITE, BUBBLE, BLUE_BUBBLE, FLASHING_BUBBLE, DARKNUT, BLUE_DARKNUT,
		GEL, GIBDO, GORIYA, BLUE_GORIYA, KEESE, LANMOLA, BLUE_LANMOLA, LIKE_LIKE,
		MOLDORM, PATRA, BABY_PATRA, POLS_VOICE, ROPE, FLASHING_ROPE, STALFOS,
		STONE_STATUE, VIRE, WALLMASTER, WIZZROBE, BLUE_WIZZROBE, ZOL, AQUAMENTUS,
		DODONGO, MANHANDLA, GLEEOK, DIGDOGGER, GOHMA, GANON, MINI_DIGDOGGER, BLADE_TRAP}
enum ITEM_TYPE {GREEN_RUPEE,BLUE_RUPEE,HEART,BOMB,TIMER,FAIRY, KEY, ORANGE_MAP, BLUE_MAP,
		COMPASS, NULL}
enum KEY_ITEM_TYPE {NULL,WOODEN_SWORD, WHITE_SWORD, MAGICAL_SWORD, 
		WOODEN_SHIELD,MAGICAL_SHIELD,WOODEN_BOOMERANG,MAGICAL_BOOMERANG,
		BOMB,BOW,WOODEN_ARROW,SILVER_ARROW,BLUE_CANDLE,RED_CANDLE,RECORDER,
		FOOD,LETTER,RED_POTION,BLUE_POTION,MAGICAL_ROD,DOOR_KEY, HEART_CONTAINER, HEART}
enum KILL_METHOD {OTHER, BOMB}
enum BLOCK_ATTACK_LEVEL {IMPOSSIBLE, WOODEN_SHIELD, MAGICAL_SHIELD}
