extends Node

class_name ENUM

enum HEART_AMOUNT {EMPTY, HALF, FULL}
enum ENEMY_TYPE {TEKTITE, OCTOROK, ZORA, LEEVER, BLUE_LEEVER, ARMOS, BOULDER, 
		GHINI, LYNEL, BLUE_LYNEL, MOBLIN, BLUE_MOBLIN, BLUE_OCTOROK, PEAHAT,
		BLUE_TEKTITE, BUBBLE, BLUE_BUBBLE, FLASHING_BUBBLE, DARKNUT, BLUE_DARKNUT,
		GEL, GIBDO, GORIYA, BLUE_GORIYA, KEESE, LANMOLA, BLUE_LANMOLA, LIKE_LIKE,
		MOLDORM, PATRA, BABY_PATRA, POLS_VOICE, ROPE, FLASHING_ROPE, STALFOS,
		STONE_STATUE, VIRE, WALLMASTER, WIZZROBE, BLUE_WIZZROBE, ZOL, AQUAMENTUS,
		DODONGO, MANHANDLA, GLEEOK, DIGDOGGER, GOHMA, GANON, MINI_DIGDOGGER, BLADE_TRAP}

enum ITEM_TYPE { BOMB, BLUE_CANDLE, BLUE_POTION, BLUE_RUPEE, BOW,
	COMPASS, DOOR_KEY, FAIRY, FOOD, GREEN_RUPEE, HEART, HEART_CONTAINER, LETTER,
	MAGICAL_BOOMERANG, MAGICAL_ROD, MAGICAL_SHIELD, MAGICAL_SWORD, ORANGE_MAP,
	RECORDER, RED_CANDLE, RED_POTION, SILVER_ARROW, TIMER, TRIFORCE_PIECE,
	WHITE_SWORD, WOODEN_ARROW, WOODEN_BOOMERANG, WOODEN_SHIELD, WOODEN_SWORD,
	NULL
}
enum KILL_METHOD {OTHER, BOMB}
enum BLOCK_ATTACK_LEVEL {IMPOSSIBLE, WOODEN_SHIELD, MAGICAL_SHIELD}
