extends Node

class_name ENUM

enum HEART_AMOUNT {EMPTY, HALF, FULL}
enum ENEMY_TYPE {TEKTITE, OCTOROK, ZORA, LEEVER}
enum ITEM_TYPE {GREEN_RUPEE,BLUE_RUPEE,HEART}
enum KEY_ITEM_TYPE {NULL,WOODEN_SWORD}
