extends Node

class_name ENUM

enum HEART_AMOUNT {EMPTY, HALF, FULL}
enum ENEMY_TYPE {TEKTITE, OCTOROK, ZORA, LEEVER}
enum ITEM_TYPE {GREEN_RUPEE,BLUE_RUPEE,HEART}
enum KEY_ITEM_TYPE {NULL,WOODEN_SWORD, WHITE_SWORD, MAGICAL_SWORD, 
		WOODEN_SHIELD,MAGICAL_SHIELD,WOODEN_BOOMERANG,MAGICAL_BOOMERANG,
		BOMB,BOW,WOODEN_ARROW,SILVER_ARROW,BLUE_CANDLE,RED_CANDLE,RECORDER,
		FOOD,LETTER,RED_POTION,BLUE_POTION,MAGICAL_ROD,DOOR_KEY}
